using System;
using System.Collections.Generic;
namespace REIC
{
    ////////////////////////////////////////////////////////////////////////////////////////////////////////
    //FileName: ResultSolarEnergyData.cs
    //FileType: Visual C# Source file
    //Author : Bucnaru Raluca
    //Description : yearly energy generated by the entire solar panel system
    //////////////////////////////////////////////////////////////////////////////////////
    class ResultSolarEnergyData : ResultEnergyData
    {
        public override IEnumerable<double> MonthlyEnergyProduced { get; }

        /// The panel model used
        public SolarPanel SolarPanel { get; }

        /// The optimal solar panel placements
        public List<GeographicalPoint> PanelLocation { get; }


        // TODO replace
        public override double MaximumYearlyEnergy { get { throw new NotImplementedException(); } }


        // things about the suitability could be added
        // eg.
        // bool IsSuitable;
        // string NotSuitableReason;
    }
}
